;
; File generated by cc65 v 2.19 - Git c2556bb5e
;
	.fopt		compiler,"cc65 v 2.19 - Git c2556bb5e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_printchar
	.export		_print
	.export		__start

.segment	"RODATA"

S0001:
	.byte	$48,$65,$6C,$6C,$6F,$2C,$20,$57,$6F,$72,$6C,$64,$21,$0A,$00

; ---------------------------------------------------------------
; void __near__ printchar (char c)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_printchar: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	sta     $FFF8
	ldx     #$00
	lda     #$01
	sta     $FFF9
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ print (const char *str)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print: near

.segment	"CODE"

	jsr     pushax
	jmp     L0004
L0002:	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	pha
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	pla
	jsr     _printchar
L0004:	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jne     L0002
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ _start (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__start: near

.segment	"CODE"

	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _print
	jmp     L0002
L0002:	jmp     L0002
	rts

.endproc

